name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Create Builds Directory
      run: mkdir -p Builds

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/Builds/build" >> "$GITHUB_OUTPUT"
        echo "test-output-dir=${{ github.workspace }}/Builds/test" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --output-on-failure --test-dir ${{ steps.strings.outputs.build-output-dir }} --build-config ${{ matrix.build_type }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-and-test-artifacts
        path: |
          ${{ steps.strings.outputs.build-output-dir }}
          ${{ steps.strings.outputs.test-output-dir }}

    - name: Move Build Artifacts to Repository Folder
      run: |
        mkdir -p ${{ github.workspace }}/binaries
        mv ${{ steps.strings.outputs.build-output-dir }}/* ${{ github.workspace }}/binaries/

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Set Git remote URL to SSH
      run: git remote set-url origin git@github.com:devgabrielsborges/RegistraAi.git

    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Add build artifacts"
        branch: main
        file_pattern: binaries/
